from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding='utf-8')


def test_tablet_menu_enters_explicit_session_profile():
    shell = read('templates/layouts/left_bar.html')
    dashboard = read('routes/dashboard/dashboard.py')
    launchpad = read('routes/launchpad/launchpad.py')

    assert "url_for('dashboard_bp.enable_tablet_mode')" in shell
    assert "session['tablet_mode'] = True" in dashboard
    assert 'session.modified = True' in dashboard
    assert "if not session.get('tablet_mode')" in launchpad
    assert "redirect(url_for('dashboard_bp.enable_tablet_mode'))" in launchpad
    assert "session['tablet_mode'] = True" not in launchpad


def test_tablet_profile_uses_full_physical_width_with_1024_behavior_reference():
    css = read('static/css/tablet_mode.css')
    runtime = read('static/js/tablet_runtime.js')

    assert '--tablet-profile-reference-width: 1024px' in css
    assert 'width: 100% !important' in css
    assert 'max-width: none !important' in css
    assert 'container-name: orbis-tablet-viewport' not in css
    assert 'TABLET_REFERENCE_WIDTH = 1024' in runtime
    assert "root.classList.add('tablet-full-width-profile')" in runtime
    assert "document.body.dataset.tabletProfile = 'full-width'" in runtime


def test_module_breakpoints_are_mirrored_to_reference_profile_not_container_width():
    generated = read('static/css/tablet_responsive.css')
    builder = read('scripts/build_tablet_responsive.py')

    assert 'AUTO-GENERATED by scripts/build_tablet_responsive.py' in generated
    assert 'Full-width tablet mode' in generated
    assert 'reference match: (max-width:1050px)' in generated
    assert 'html.tablet-mode .bo-kpis {grid-template-columns:repeat(2,1fr)}' in generated
    assert 'reference match: (max-width:1200px)' in generated
    assert 'html.tablet-mode .clients-page {margin-left:0;padding-top:80px;}' in generated
    assert '@container orbis-tablet-viewport' not in generated
    assert 'REFERENCE_WIDTH = 1024.0' in builder
    assert 'scope_selector' in builder


def test_tablet_shell_replaces_sidebar_with_section_dock():
    shell = read('templates/layouts/left_bar.html')
    css = read('static/css/tablet_mode.css')
    runtime = read('static/js/tablet_runtime.js')

    assert 'aria-label="Secciones del sistema"' in shell
    for section in ('sales', 'inventory', 'purchases', 'control', 'settings'):
        assert f'data-tablet-section="{section}"' in shell
    assert 'tablet-section-sheet' in shell
    assert '#app-sidebar' in css and 'display: none !important' in css
    assert 'initSectionDock' in runtime
    assert "document.querySelectorAll('#app-sidebar [data-nav-section]')" in runtime
    assert "link.className = 'tablet-section-link'" in runtime


def test_full_width_tablet_assets_load_after_module_css_via_shared_chrome():
    shell = read('templates/layouts/left_bar.html')
    launchpad = read('templates/launchpad/index.html')
    head = read('templates/layouts/app_head_assets.html')

    assert "css/tablet_mode.css" in shell
    assert "css/tablet_responsive.css" in shell
    assert shell.index("css/app_final.css") < shell.index("css/tablet_mode.css") < shell.index("css/tablet_responsive.css")
    assert "css/tablet_mode.css" in launchpad and "css/tablet_responsive.css" in launchpad
    assert "root.classList.toggle('tablet-full-width-profile', tabletMode)" in head
    assert '20260827-tablet10' in head and '20260827-tablet10' in shell
